# Generated by Django 3.0.4 on 2020-04-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIserver', '0002_auto_20200408_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
