# Generated by Django 3.0.4 on 2020-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIserver', '0003_remove_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
